version: '3'
services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: formbox
    ports:
      - "5432:5432"
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"