version: '3'
services:
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: formbox
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - datavolume:/data/postgres
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
volumes:
  datavolume: