version: '3'
services:
  app:
    build: .
    environment:
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: formbox
      SMTP_HOST: mailcatcher
      SMTP_PORT: 1025
      SMTP_TLS_ENABLED: False
      SMTP_FROM: no-reply@formbox.dev
      SMS_ENABLED: False
      HOST: localhost
      HOST_PROTOCOL: http
      CORS_HOSTS: localhost
      SECRET_KEY: secret
    ports:
      - 80:80
